vim.keymap.set("n", "<leader>ha", function ()
   require('harpoon.mark').add_file() 
end)
vim.keymap.set("n", "<leader>hm", function ()
    require('harpoon.ui').toggle_quick_menu()
end)

vim.keymap.set("n", "<leader>h1", function ()
    require('harpoon.ui').nav_file(1)
end)
vim.keymap.set("n", "<leader>h2", function ()
    require('harpoon.ui').nav_file(2)
end)
vim.keymap.set("n", "<leader>h3", function ()
    require('harpoon.ui').nav_file(3)
end)
vim.keymap.set("n", "<leader>h4", function ()
    require('harpoon.ui').nav_file(4)
end)

vim.keymap.set("n", "<leader>fh", ":Telescope harpoon marks<CR>")
