
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Default Applications
env = BROWSER,brave
env = TERMINAL,ghostty
env = EDITOR,nvim
env = VISUAL,nvim
env = FILEBROWSER,xplr
env = WORK_DIR,/mnt/disposable/code/
