$screenshot = flameshot
$mainMod = SUPER
$exetui = ghostty -e
$terminal = ghostty
$fileManager = nautilus
$menu = rofi -show combi
$browser = brave
$editor = nvim
$bt = bluetui
$right_overlay = term-overlay-right


#tray binds
bind = $mainMod SHIFT, C, exec, $right_overlay btop #rofi: Open System Monitor (BTOP)
bind = $mainMod SHIFT, N, exec, $right_overlay impala #rofi: Open Network Manager (Impala)
bind = $mainMod SHIFT, V, exec, $right_overlay wiremix #rofi: Open Volume Mixer (Wiremix)
bind = $mainMod SHIFT, U, exec, $right_overlay paru -Syu #rofi: Update System (Paru)
bind = $mainMod SHIFT, X, exec, ~/.config/eww/scripts/toggle_var.sh tray_expanded #rofi: Toggle System Tray

bind = $mainMod, T, exec, $terminal #rofi: Open Terminal (Ghostty)
bind = $mainMod, Q, killactive, #rofi: Close Active Window

bind = $mainMod, E, exec, $fileManager #rofi: Open File Manager (Nautilus)
bind = $mainMod, V, togglefloating, #rofi: Toggle Floating Mode
bind = $mainMod, R, exec, $menu #rofi: Open App Launcher (Rofi)
bind = $mainMod, B, exec, $browser #rofi: Open Web Browser (Brave)
bind = $mainMod SHIFT, B, exec, $right_overlay $bt #rofi: Open Bluetooth Manager (Bluetui)
bind = $mainMod, P, pseudo, # dwindle #rofi: Toggle Pseudo-Tiling
bind = $mainMod SHIFT, P, exec, $screenshot gui #rofi: Take a Screenshot (Flameshot)
bind = $mainMod, J, layoutmsg, togglesplit # dwindle #rofi: Toggle Layout Split

bind = $mainMod, left, movefocus, l #rofi: Focus Window Left
bind = $mainMod, right, movefocus, r #rofi: Focus Window Right
bind = $mainMod, up, movefocus, u #rofi: Focus Window Up
bind = $mainMod, down, movefocus, d #rofi: Focus Window Down

bind = $mainMod, 1, workspace, 1 #rofi: Go to Workspace 1
bind = $mainMod, 2, workspace, 2 #rofi: Go to Workspace 2
bind = $mainMod, 3, workspace, 3 #rofi: Go to Workspace 3
bind = $mainMod, 4, workspace, 4 #rofi: Go to Workspace 4
bind = $mainMod, 5, workspace, 5 #rofi: Go to Workspace 5
bind = $mainMod, 6, workspace, 6 #rofi: Go to Workspace 6
bind = $mainMod, 7, workspace, 7 #rofi: Go to Workspace 7
bind = $mainMod, 8, workspace, 8 #rofi: Go to Workspace 8
bind = $mainMod, 9, workspace, 9 #rofi: Go to Workspace 9
bind = $mainMod, 0, workspace, 10 #rofi: Go to Workspace 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1 #rofi: Move Window to Workspace 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2 #rofi: Move Window to Workspace 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3 #rofi: Move Window to Workspace 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4 #rofi: Move Window to Workspace 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5 #rofi: Move Window to Workspace 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6 #rofi: Move Window to Workspace 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7 #rofi: Move Window to Workspace 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8 #rofi: Move Window to Workspace 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9 #rofi: Move Window to Workspace 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10 #rofi: Move Window to Workspace 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic #rofi: Toggle Scratchpad Workspace
bind = $mainMod SHIFT, S, movetoworkspace, special:magic #rofi: Move Window to Scratchpad

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1 #rofi: Next Workspace (Scroll)
bind = $mainMod, mouse_up, workspace, e-1 #rofi: Prev Workspace (Scroll)

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow #rofi: Drag Window (LMB)
bindm = $mainMod, mouse:273, resizewindow #rofi: Resize Window (RMB)

