set-window-option -g mode-keys vi
set -g prefix C-Space
bind C-Space send-prefix
unbind C-b
set -g history-limit 9999999
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
unbind -n MouseDrag1Pane
unbind '"'
unbind %
bind-key ) split-window -vc "#{pane_current_path}"
bind-key a split-window -vc "#{pane_current_path}"
bind-key ( split-window -hc "#{pane_current_path}"
bind-key s split-window -hc "#{pane_current_path}"

bind 1 run-shell "~/.config/scripts/tmux_wchanger 1"
bind 2 run-shell "~/.config/scripts/tmux_wchanger 2"
bind 3 run-shell "~/.config/scripts/tmux_wchanger 3"
bind 4 run-shell "~/.config/scripts/tmux_wchanger 4"
bind 5 run-shell "~/.config/scripts/tmux_wchanger 5"

bind-key C-Space switch-client -l
bind Space run-shell "tmux neww ~/.config/scripts/tmux_sessionizer"
bind l select-pane -R
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U

unbind-key -T copy-mode-vi v
unbind-key c
unbind-key -T root c
unbind-key [
bind c run-shell "~/.config/scripts/tmux_relnum_visual"
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind -r w resize-pane -D 15
bind -r e resize-pane -U 15
bind -r q resize-pane -L 15
bind -r r resize-pane -R 15
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard > /dev/null'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard > /dev/null'
bind-key C-p run-shell -t 'xclip -out -selection clipboard | tmux load-buffer - ; tmux paste-buffer'

unbind n
bind-key n split-window -h "nvim ~/Documents/Notes/QuickNote.md"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @logging-path '#{pane_current_path}'
set -g @save-complete-history-path '#{pane_current_path}'
set -g @screen-capture-path '#{pane_current_path}'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
